### ISSUE TITLE
User Story:  As a director, I need recommendations for the composition and organization of the first value stream, potentially starting from some existing charters.

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#22]
## Review existing Charters and RACI

- Synoptic Reporting IPT Charter
- eGFR Cystatin C IPT Charter
- CIDMO IPT RACI Template

### Identify competencies and directorates

- Identify competencies necessary to support IPT.
- Identify supporting programs.
- Identify supporting Program Office.

**Comment by jamesmrollins** [comment]
As per discussion with @maneyb1 on 2/28- we will convert a team charter and IPT SOP into Lean-Agile artifacts such as a Value Stream Canvas and an Epic.  

- This conversion needs to be done in time for the discussion with Dr. Cillessen on 3/1. 
- We also need to define the Epic-User Story-Feature-Task definition and hierarchy.  
- Need to define our tagging system as well.
- Clarify the difference between an IPT chartered team versus a "standing team."
- Identify the primacy of the value stream.

**Comment by maneyb1** [comment]
### IPT vs Value Stream 
In CIDMO, IPT is the organizing construct for getting work done.  
In SAFe, the organizing construct is the value stream 
Teams align to the value stream 
Teams pull work off the backlog 
 
### OIT is on the ART 
OIT partners can do dev and testing 
Testing sites have questions, questions go back to clinical SME, Testing and deployment team will make changes 
CLIN2 team codes the actual templates 
There are a few CACs in CIDMO that can do this.  
Elizabeth Griffith - leads the formerly named CLIN2 team, now organized in OIT as: 
Office of Information Technology (OIT), Development, Security, and Operations (DevSecOps), Software Product Management (SPM), Health Portfolio, Provider Systems Product Line, Computerized Patient Record System (CPRS) Sub-Product Lines 

### Current Engagement Patterns 
We have high profile, busy business owners engage. A few meetings are needed to get the right people, the right problem and the right target outcomes 
Level of stakeholder engagement varies - Heavily involved business owners can fill product owner roles 
Stakeholders generally want to define MVP at this point however it usually takes 10 hours to get the clinical guidelines identified and the Objectives and Measures approved 
Nephrology is currently working to get the right problem and outcomes in the charter 
Challenge is to not get to solutions to quickly 
VISN 10 was 20hrs week engagement with SMEs 

### KPIs 
KPIs are concern of the business owner and are determined before the team picks up the work 
This is not current practice because it is difficult to elicit this from business owners 
The IHPI team identifies how we will know we have met KPIs 
Cystatin C Use Case 
- Appropriate use of cystatin C 
- Cost Savings 

Link to meeting notes: [https://dvagov.sharepoint.com/sites/CopyofMPKanban/_layouts/15/Doc.aspx?sourcedoc={0984b121-cdf3-4705-9b74-350b46e60e33}&action=edit&wd=target%282.%20VS%20and%20ART%20Identification%2FPrepare%20for%20ART%20ID.one%7Cdee75e7d-37e7-49ef-ad47-8b501a3634e4%2FMeeting%20Continue%20to%20discuss%20starting%20point%20for%20SAFe%7Cb5cc8e8b-3637-41ea-85ad-a8790bc1fb32%2F%29&wdorigin=703]

**Comment by jamesmrollins** [comment]
Sprint Planning Mtg 3/2

- We have provided some useful examples of how IHP work could be organized into a Template Value Stream and an Implementation Value Stream.
- Future VS may need to be developed to round out the full scope of IHP work.
- This will be done during our ART organization workshops through March.
- We will close this card and create another card for future sprint.
