### ISSUE TITLE
User Story:  We need to understand KBS/S&I workflows so we can integrate into the IHP value stream

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#33]
# Deliverables

- [x] Contact Apurva Desei, Catherine Hoang and set up a meeting (Brenna)
- [x] Sketch their workflow (James)
- [x] Use workflow to inform whether we need a new DVS or an addition to an existing proposed DVS.
- [x] Get access to work tracking or backlog system, if exists.

## Currently the division splits themselves into two concerns

- Terminology 
- Clinical Decision Support
- There is potentially some turbulence if we bring them together based on potential problems between the two concerns.

**Comment by maneyb1** [comment]
- [x] Follow up meeting with Terminology Team
- [ ] Review Apurva's diagram
- [ ] Validate KBS assertion that IHP is missing a 5th component
- [ ] Get list of BPMN+ models from Ken Ruben 
- [ ] Link whiteboard notes with meeting notes

### Answer questions about what this is about 
- Several team members took the two trainings 
- Apurva - used a clock analogy where CIDMO is responsible between 9 am and 9 PM but we have dependencies on OIT for 9pm - 9am.  
- Steve commented that Resources and authority are two barriers to standardizing and measuring our development value streams 

###  Organization of KBS work 
- KBS is organizes their work into 4 branches 
- Standards and Interoperability 
- Terminology 
- Clinical Decision Support 
- Informatics Architecture 

### Coded Health Factors 
- Encoded health factors were done for CERNER 
- They are not implemented in VA because of delays with the necessary VistA patch.  
- OIT has delayed due to dependency analysis with CPRSv32 

###  Standards: 
- Creates guides to take advantage of standards, such as FHIR 

### Clinical Decision Support 
- CDS - standardization of how information is displayed and captured 
- Develops above the line artifact that humans deal with (Rule, order set, documentation template, website, etc)
- CDS tracks discrete projects 
- Adhoc consultation is how they resource IHP 

 ### Terminology 
- Processes are more formal in terminology because there are versions which makes the processing and update activities routine.  
- Terminology has a request tracking process…

**Comment by jamesmrollins** [comment]
Card split to #50
