### ISSUE TITLE
Enabler:  Training Schedule and Budget for Training MOI

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#48]
Reference #24

- [x] Need to schedule training by role.
- [x] Determine budget needs 
- [x] Get management approval for budget

**Comment by maneyb1** [comment]
- [x] Schedule ideal training events and SAFe ceremonies
- [x] Confirm availability of training team
- [x] Identify people to train
- [x] Confirm identified trainees availability 
~~- [ ] Submit training forms~~
~~- [ ] Pay for training~~

**Comment by maneyb1** [comment]
- [x] Send draft schedule of trainings to Tas - have meeting scheduled 3/23 to discuss availability of his team to support

**Comment by maneyb1** [comment]
Tas recommends we seek out additional scrum master training and identify contract strategy because the SAFe scrum master training assumes basic scrum master skills and teaches how to apply those skills in scaled agile. 

- [x] Investigating Scrum master training options in VA (linked-in learning/TMS) 
  - [x] Use LCMT as scrum master coaches for first increment
  - [x] identify options in contract vehicles

- [x] Connect Charlene and Tas to figure out how to purchase training in coordination with Richard
- [x] Removed the 3 leading SAFe cohort, as we expect the 2nd PI planning to include roughly the same members as the first. 

- [x] Aimee getting budget approval (~10k) from Jonathan

**Comment by maneyb1** [comment]
Draft list of cohort 1/2  Leading SAFe participants:
https://dvagov.sharepoint.com/sites/CopyofMPKanban/Lists/SAFe%20Onboarding/SAFe%20Class%20Cohorts.aspx?viewid=3be0cda6%2Ddd3e%2D4b4a%2Da3a2%2D3f31e4555282

Need to review training budget - may need to request 10k
Need to discuss who should pay for training for Program Office People

**Comment by maneyb1** [comment]
Brenna added spend plan and work item into SP lists on 3/28

**Comment by maneyb1** [comment]
@aimeebenson - have Charlene send draft SF182 to brenna, Brenna will email candidate participants asking them to confirm their availability by completing 182 and sending to Charlene

Done

**Comment by maneyb1** [comment]
Working on purchase card issue to actually buy the training licenses - meeting on Friday to try to resolve with purchase card holders.
